/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __PINCTRL_MTK_MT8127_H
#define __PINCTRL_MTK_MT8127_H

#include <linux/pinctrl/pinctrl.h>
#include "pinctrl-mtk-common.h"

static const struct mtk_desc_pin mtk_pins_mt8127[] = {
	MTK_PIN(
		PINCTRL_PIN(0, "PWRAP_SPI0_MI"),
		"P22", "mt8127",
		MTK_EINT_FUNCTION(0, 22),
		MTK_FUNCTION(0, "GPIO0"),
		MTK_FUNCTION(1, "PWRAP_SPIDO"),
		MTK_FUNCTION(2, "PWRAP_SPIDI")
	),
	MTK_PIN(
		PINCTRL_PIN(1, "PWRAP_SPI0_MO"),
		"M22", "mt8127",
		MTK_EINT_FUNCTION(0, 23),
		MTK_FUNCTION(0, "GPIO1"),
		MTK_FUNCTION(1, "PWRAP_SPIDI"),
		MTK_FUNCTION(2, "PWRAP_SPIDO")
	),
	MTK_PIN(
		PINCTRL_PIN(2, "PWRAP_INT"),
		"L23", "mt8127",
		MTK_EINT_FUNCTION(0, 24),
		MTK_FUNCTION(0, "GPIO2")
	),
	MTK_PIN(
		PINCTRL_PIN(3, "PWRAP_SPI0_CK"),
		"N23", "mt8127",
		MTK_EINT_FUNCTION(0, 25),
		MTK_FUNCTION(0, "GPIO3"),
		MTK_FUNCTION(1, "PWRAP_SPICK_I")
	),
	MTK_PIN(
		PINCTRL_PIN(4, "PWRAP_SPI0_CSN"),
		"N22", "mt8127",
		MTK_EINT_FUNCTION(0, 26),
		MTK_FUNCTION(0, "GPIO4"),
		MTK_FUNCTION(1, "PWRAP_SPICS_B_I")
	),
	MTK_PIN(
		PINCTRL_PIN(5, "PWRAP_SPI0_CK2"),
		"L19", "mt8127",
		MTK_EINT_FUNCTION(0, 27),
		MTK_FUNCTION(0, "GPIO5"),
		MTK_FUNCTION(1, "PWRAP_SPICK2_I"),
		MTK_FUNCTION(2, "ANT_SEL1"),
		MTK_FUNCTION(3, "VDEC_TEST_CK"),
		MTK_FUNCTION(7, "DBG_MON_B[0]")
	),
	MTK_PIN(
		PINCTRL_PIN(6, "PWRAP_SPI0_CSN2"),
		"M23", "mt8127",
		MTK_EINT_FUNCTION(0, 28),
		MTK_FUNCTION(0, "GPIO6"),
		MTK_FUNCTION(1, "PWRAP_SPICS2_B_I"),
		MTK_FUNCTION(2, "ANT_SEL0"),
		MTK_FUNCTION(3, "MM_TEST_CK"),
		MTK_FUNCTION(7, "DBG_MON_B[1]")
	),
	MTK_PIN(
		PINCTRL_PIN(7, "AUD_CLK_MOSI"),
		"K23", "mt8127",
		MTK_EINT_FUNCTION(0, 29),
		MTK_FUNCTION(0, "GPIO7"),
		MTK_FUNCTION(1, "AUD_CLK"),
		MTK_FUNCTION(2, "ADC_CK")
	),
	MTK_PIN(
		PINCTRL_PIN(8, "AUD_DAT_MISO"),
		"K24", "mt8127",
		MTK_EINT_FUNCTION(0, 30),
		MTK_FUNCTION(0, "GPIO8"),
		MTK_FUNCTION(1, "AUD_MISO"),
		MTK_FUNCTION(2, "ADC_DAT_IN"),
		MTK_FUNCTION(3, "AUD_MOSI")
	),
	MTK_PIN(
		PINCTRL_PIN(9, "AUD_DAT_MOSI"),
		"K22", "mt8127",
		MTK_EINT_FUNCTION(0, 31),
		MTK_FUNCTION(0, "GPIO9"),
		MTK_FUNCTION(1, "AUD_MOSI"),
		MTK_FUNCTION(2, "ADC_WS"),
		MTK_FUNCTION(3, "AUD_MISO")
	),
	MTK_PIN(
		PINCTRL_PIN(10, "RTC32K_CK"),
		"R21", "mt8127",
		MTK_EINT_FUNCTION(0, 32),
		MTK_FUNCTION(0, "GPIO10"),
		MTK_FUNCTION(1, "RTC32K_CK")
	),
	MTK_PIN(
		PINCTRL_PIN(11, "WATCHDOG"),
		"P24", "mt8127",
		MTK_EINT_FUNCTION(0, 33),
		MTK_FUNCTION(0, "GPIO11"),
		MTK_FUNCTION(1, "WATCHDOG")
	),
	MTK_PIN(
		PINCTRL_PIN(12, "SRCLKENA"),
		"R22", "mt8127",
		MTK_EINT_FUNCTION(0, 34),
		MTK_FUNCTION(0, "GPIO12"),
		MTK_FUNCTION(1, "SRCLKENA")
	),
	MTK_PIN(
		PINCTRL_PIN(13, "SRCLKENAI"),
		"P23", "mt8127",
		MTK_EINT_FUNCTION(0, 35),
		MTK_FUNCTION(0, "GPIO13"),
		MTK_FUNCTION(1, "SRCLKENAI")
	),
	MTK_PIN(
		PINCTRL_PIN(14, "URXD2"),
		"U19", "mt8127",
		MTK_EINT_FUNCTION(0, 36),
		MTK_FUNCTION(0, "GPIO14"),
		MTK_FUNCTION(1, "URXD2"),
		MTK_FUNCTION(2, "DPI_D5"),
		MTK_FUNCTION(3, "UTXD2"),
		MTK_FUNCTION(5, "SRCCLKENAI2"),
		MTK_FUNCTION(6, "KROW4")
	),
	MTK_PIN(
		PINCTRL_PIN(15, "UTXD2"),
		"U20", "mt8127",
		MTK_EINT_FUNCTION(0, 37),
		MTK_FUNCTION(0, "GPIO15"),
		MTK_FUNCTION(1, "UTXD2"),
		MTK_FUNCTION(2, "DPI_HSYNC"),
		MTK_FUNCTION(3, "URXD2"),
		MTK_FUNCTION(6, "KROW5")
	),
	MTK_PIN(
		PINCTRL_PIN(16, "URXD3"),
		"U18", "mt8127",
		MTK_EINT_FUNCTION(0, 38),
		MTK_FUNCTION(0, "GPIO16"),
		MTK_FUNCTION(1, "URXD3"),
		MTK_FUNCTION(2, "DPI_DE"),
		MTK_FUNCTION(3, "UTXD3"),
		MTK_FUNCTION(4, "UCTS2"),
		MTK_FUNCTION(5, "PWM3"),
		MTK_FUNCTION(6, "KROW6")
	),
	MTK_PIN(
		PINCTRL_PIN(17, "UTXD3"),
		"R18", "mt8127",
		MTK_EINT_FUNCTION(0, 39),
		MTK_FUNCTION(0, "GPIO17"),
		MTK_FUNCTION(1, "UTXD3"),
		MTK_FUNCTION(2, "DPI_VSYNC"),
		MTK_FUNCTION(3, "URXD3"),
		MTK_FUNCTION(4, "URTS2"),
		MTK_FUNCTION(5, "PWM4"),
		MTK_FUNCTION(6, "KROW7")
	),
	MTK_PIN(
		PINCTRL_PIN(18, "PCM_CLK"),
		"U22", "mt8127",
		MTK_EINT_FUNCTION(0, 40),
		MTK_FUNCTION(0, "GPIO18"),
		MTK_FUNCTION(1, "PCM_CLK0"),
		MTK_FUNCTION(2, "DPI_D4"),
		MTK_FUNCTION(3, "I2SIN1_BCK0"),
		MTK_FUNCTION(4, "I2SOUT_BCK"),
		MTK_FUNCTION(5, "CONN_DSP_JCK"),
		MTK_FUNCTION(6, "IR"),
		MTK_FUNCTION(7, "DBG_MON_A[0]")
	),
	MTK_PIN(
		PINCTRL_PIN(19, "PCM_SYNC"),
		"U23", "mt8127",
		MTK_EINT_FUNCTION(0, 41),
		MTK_FUNCTION(0, "GPIO19"),
		MTK_FUNCTION(1, "PCM_SYNC"),
		MTK_FUNCTION(2, "DPI_D3"),
		MTK_FUNCTION(3, "I2SIN1_LRCK"),
		MTK_FUNCTION(4, "I2SOUT_LRCK"),
		MTK_FUNCTION(5, "CONN_DSP_JINTP"),
		MTK_FUNCTION(6, "EXT_COL"),
		MTK_FUNCTION(7, "DBG_MON_A[1]")
	),
	MTK_PIN(
		PINCTRL_PIN(20, "PCM_RX"),
		"V22", "mt8127",
		MTK_EINT_FUNCTION(0, 42),
		MTK_FUNCTION(0, "GPIO20"),
		MTK_FUNCTION(1, "PCM_RX"),
		MTK_FUNCTION(2, "DPI_D1"),
		MTK_FUNCTION(3, "I2SIN1_DATA_IN"),
		MTK_FUNCTION(4, "PCM_TX"),
		MTK_FUNCTION(5, "CONN_DSP_JDI"),
		MTK_FUNCTION(6, "EXT_MDIO"),
		MTK_FUNCTION(7, "DBG_MON_A[2]")
	),
	MTK_PIN(
		PINCTRL_PIN(21, "PCM_TX"),
		"U21", "mt8127",
		MTK_EINT_FUNCTION(0, 43),
		MTK_FUNCTION(0, "GPIO21"),
		MTK_FUNCTION(1, "PCM_TX"),
		MTK_FUNCTION(2, "DPI_D2"),
		MTK_FUNCTION(3, "I2SOUT_DATA_OUT"),
		MTK_FUNCTION(4, "PCM_RX"),
		MTK_FUNCTION(5, "CONN_DSP_JMS"),
		MTK_FUNCTION(6, "EXT_MDC"),
		MTK_FUNCTION(7, "DBG_MON_A[3]")
	),
	MTK_PIN(
		PINCTRL_PIN(22, "EINT0"),
		"AB19", "mt8127",
		MTK_EINT_FUNCTION(0, 0),
		MTK_FUNCTION(0, "GPIO22"),
		MTK_FUNCTION(1, "PWM1"),
		MTK_FUNCTION(2, "DPI_CK"),
		MTK_FUNCTION(4, "EXT_TXD0"),
		MTK_FUNCTION(5, "CONN_DSP_JDO"),
		MTK_FUNCTION(7, "DBG_MON_A[4]")
	),
	MTK_PIN(
		PINCTRL_PIN(23, "EINT1"),
		"AA21", "mt8127",
		MTK_EINT_FUNCTION(0, 1),
		MTK_FUNCTION(0, "GPIO23"),
		MTK_FUNCTION(1, "PWM2"),
		MTK_FUNCTION(2, "DPI_D12"),
		MTK_FUNCTION(4, "EXT_TXD1"),
		MTK_FUNCTION(5, "CONN_MCU_TDO"),
		MTK_FUNCTION(7, "DBG_MON_A[5]")
	),
	MTK_PIN(
		PINCTRL_PIN(24, "EINT2"),
		"AA19", "mt8127",
		MTK_EINT_FUNCTION(0, 2),
		MTK_FUNCTION(0, "GPIO24"),
		MTK_FUNCTION(1, "CLKM0"),
		MTK_FUNCTION(2, "DPI_D13"),
		MTK_FUNCTION(4, "EXT_TXD2"),
		MTK_FUNCTION(5, "CONN_MCU_DBGACK_N"),
		MTK_FUNCTION(6, "KCOL4"),
		MTK_FUNCTION(7, "DBG_MON_A[6]")
	),
	MTK_PIN(
		PINCTRL_PIN(25, "EINT3"),
		"Y19", "mt8127",
		MTK_EINT_FUNCTION(0, 3),
		MTK_FUNCTION(0, "GPIO25"),
		MTK_FUNCTION(1, "CLKM1"),
		MTK_FUNCTION(2, "DPI_D14"),
		MTK_FUNCTION(3, "SPI_MI"),
		MTK_FUNCTION(4, "EXT_TXD3"),
		MTK_FUNCTION(5, "CONN_MCU_DBGI_N"),
		MTK_FUNCTION(6, "KCOL5"),
		MTK_FUNCTION(7, "DBG_MON_A[7]")
	),
	MTK_PIN(
		PINCTRL_PIN(26, "EINT4"),
		"V21", "mt8127",
		MTK_EINT_FUNCTION(0, 4),
		MTK_FUNCTION(0, "GPIO26"),
		MTK_FUNCTION(1, "CLKM2"),
		MTK_FUNCTION(2, "DPI_D15"),
		MTK_FUNCTION(3, "SPI_MO"),
		MTK_FUNCTION(4, "EXT_TXC"),
		MTK_FUNCTION(5, "CONN_MCU_TCK0"),
		MTK_FUNCTION(6, "CONN_MCU_AICE_JCKC"),
		MTK_FUNCTION(7, "DBG_MON_A[8]")
	),
	MTK_PIN(
		PINCTRL_PIN(27, "EINT5"),
		"AB22", "mt8127",
		MTK_EINT_FUNCTION(0, 5),
		MTK_FUNCTION(0, "GPIO27"),
		MTK_FUNCTION(1, "UCTS2"),
		MTK_FUNCTION(2, "DPI_D16"),
		MTK_FUNCTION(3, "SPI_CS"),
		MTK_FUNCTION(4, "EXT_RXER"),
		MTK_FUNCTION(5, "CONN_MCU_TDI"),
		MTK_FUNCTION(6, "KCOL6"),
		MTK_FUNCTION(7, "DBG_MON_A[9]")
	),
	MTK_PIN(
		PINCTRL_PIN(28, "EINT6"),
		"AA23", "mt8127",
		MTK_EINT_FUNCTION(0, 6),
		MTK_FUNCTION(0, "GPIO28"),
		MTK_FUNCTION(1, "URTS2"),
		MTK_FUNCTION(2, "DPI_D17"),
		MTK_FUNCTION(3, "SPI_CK"),
		MTK_FUNCTION(4, "EXT_RXC"),
		MTK_FUNCTION(5, "CONN_MCU_TRST_B"),
		MTK_FUNCTION(6, "KCOL7"),
		MTK_FUNCTION(7, "DBG_MON_A[10]")
	),
	MTK_PIN(
		PINCTRL_PIN(29, "EINT7"),
		"Y23", "mt8127",
		MTK_EINT_FUNCTION(0, 7),
		MTK_FUNCTION(0, "GPIO29"),
		MTK_FUNCTION(1, "UCTS3"),
		MTK_FUNCTION(2, "DPI_D6"),
		MTK_FUNCTION(3, "SDA1"),
		MTK_FUNCTION(4, "EXT_RXDV"),
		MTK_FUNCTION(5, "CONN_MCU_TMS"),
		MTK_FUNCTION(6, "CONN_MCU_AICE_JMSC"),
		MTK_FUNCTION(7, "DBG_MON_A[11]")
	),
	MTK_PIN(
		PINCTRL_PIN(30, "EINT8"),
		"Y24", "mt8127",
		MTK_EINT_FUNCTION(0, 8),
		MTK_FUNCTION(0, "GPIO30"),
		MTK_FUNCTION(1, "URTS3"),
		MTK_FUNCTION(2, "CLKM3"),
		MTK_FUNCTION(3, "SCL1"),
		MTK_FUNCTION(4, "EXT_RXD0"),
		MTK_FUNCTION(5, "ANT_SEL0"),
		MTK_FUNCTION(6, "DPI_D7"),
		MTK_FUNCTION(7, "DBG_MON_B[2]")
	),
	MTK_PIN(
		PINCTRL_PIN(31, "EINT9"),
		"W23", "mt8127",
		MTK_EINT_FUNCTION(0, 9),
		MTK_FUNCTION(0, "GPIO31"),
		MTK_FUNCTION(1, "CLKM4"),
		MTK_FUNCTION(2, "SDA2"),
		MTK_FUNCTION(3, "EXT_FRAME_SYNC"),
		MTK_FUNCTION(4, "EXT_RXD1"),
		MTK_FUNCTION(5, "ANT_SEL1"),
		MTK_FUNCTION(6, "DPI_D8"),
		MTK_FUNCTION(7, "DBG_MON_B[3]")
	),
	MTK_PIN(
		PINCTRL_PIN(32, "EINT10"),
		"W24", "mt8127",
		MTK_EINT_FUNCTION(0, 10),
		MTK_FUNCTION(0, "GPIO32"),
		MTK_FUNCTION(1, "CLKM5"),
		MTK_FUNCTION(2, "SCL2"),
		MTK_FUNCTION(3, "EXT_FRAME_SYNC"),
		MTK_FUNCTION(4, "EXT_RXD2"),
		MTK_FUNCTION(5, "ANT_SEL2"),
		MTK_FUNCTION(6, "DPI_D9"),
		MTK_FUNCTION(7, "DBG_MON_B[4]")
	),
	MTK_PIN(
		PINCTRL_PIN(33, "KPROW0"),
		"AB24", "mt8127",
		MTK_EINT_FUNCTION(0, 44),
		MTK_FUNCTION(0, "GPIO33"),
		MTK_FUNCTION(1, "KROW0"),
		MTK_FUNCTION(4, "IMG_TEST_CK"),
		MTK_FUNCTION(7, "DBG_MON_A[12]")
	),
	MTK_PIN(
		PINCTRL_PIN(34, "KPROW1"),
		"AC24", "mt8127",
		MTK_EINT_FUNCTION(0, 45),
		MTK_FUNCTION(0, "GPIO34"),
		MTK_FUNCTION(1, "KROW1"),
		MTK_FUNCTION(2, "IDDIG"),
		MTK_FUNCTION(3, "EXT_FRAME_SYNC"),
		MTK_FUNCTION(4, "MFG_TEST_CK"),
		MTK_FUNCTION(7, "DBG_MON_B[5]")
	),
	MTK_PIN(
		PINCTRL_PIN(35, "KPROW2"),
		"AD24", "mt8127",
		MTK_EINT_FUNCTION(0, 46),
		MTK_FUNCTION(0, "GPIO35"),
		MTK_FUNCTION(1, "KROW2"),
		MTK_FUNCTION(2, "DRV_VBUS"),
		MTK_FUNCTION(3, "EXT_FRAME_SYNC"),
		MTK_FUNCTION(4, "CONN_TEST_CK"),
		MTK_FUNCTION(7, "DBG_MON_B[6]")
	),
	MTK_PIN(
		PINCTRL_PIN(36, "KPCOL0"),
		"AB23", "mt8127",
		MTK_EINT_FUNCTION(0, 47),
		MTK_FUNCTION(0, "GPIO36"),
		MTK_FUNCTION(1, "KCOL0"),
		MTK_FUNCTION(7, "DBG_MON_A[13]")
	),
	MTK_PIN(
		PINCTRL_PIN(37, "KPCOL1"),
		"AC22", "mt8127",
		MTK_EINT_FUNCTION(0, 48),
		MTK_FUNCTION(0, "GPIO37"),
		MTK_FUNCTION(1, "KCOL1"),
		MTK_FUNCTION(7, "DBG_MON_B[7]")
	),
	MTK_PIN(
		PINCTRL_PIN(38, "KPCOL2"),
		"AC23", "mt8127",
		MTK_EINT_FUNCTION(0, 49),
		MTK_FUNCTION(0, "GPIO38"),
		MTK_FUNCTION(1, "KCOL2"),
		MTK_FUNCTION(2, "IDDIG"),
		MTK_FUNCTION(3, "EXT_FRAME_SYNC"),
		MTK_FUNCTION(7, "DBG_MON_B[8]")
	),
	MTK_PIN(
		PINCTRL_PIN(39, "JTMS"),
		"V18", "mt8127",
		MTK_EINT_FUNCTION(0, 50),
		MTK_FUNCTION(0, "GPIO39"),
		MTK_FUNCTION(1, "JTMS"),
		MTK_FUNCTION(2, "CONN_MCU_TMS"),
		MTK_FUNCTION(3, "CONN_MCU_AICE_JMSC")
	),
	MTK_PIN(
		PINCTRL_PIN(40, "JTCK"),
		"AA18", "mt8127",
		MTK_EINT_FUNCTION(0, 51),
		MTK_FUNCTION(0, "GPIO40"),
		MTK_FUNCTION(1, "JTCK"),
		MTK_FUNCTION(2, "CONN_MCU_TCK1"),
		MTK_FUNCTION(3, "CONN_MCU_AICE_JCKC")
	),
	MTK_PIN(
		PINCTRL_PIN(41, "JTDI"),
		"W18", "mt8127",
		MTK_EINT_FUNCTION(0, 52),
		MTK_FUNCTION(0, "GPIO41"),
		MTK_FUNCTION(1, "JTDI"),
		MTK_FUNCTION(2, "CONN_MCU_TDI")
	),
	MTK_PIN(
		PINCTRL_PIN(42, "JTDO"),
		"Y18", "mt8127",
		MTK_EINT_FUNCTION(0, 53),
		MTK_FUNCTION(0, "GPIO42"),
		MTK_FUNCTION(1, "JTDO"),
		MTK_FUNCTION(2, "CONN_MCU_TDO")
	),
	MTK_PIN(
		PINCTRL_PIN(43, "EINT11"),
		"W22", "mt8127",
		MTK_EINT_FUNCTION(0, 11),
		MTK_FUNCTION(0, "GPIO43"),
		MTK_FUNCTION(1, "CLKM4"),
		MTK_FUNCTION(2, "PWM2"),
		MTK_FUNCTION(3, "KROW3"),
		MTK_FUNCTION(4, "ANT_SEL3"),
		MTK_FUNCTION(5, "DPI_D10"),
		MTK_FUNCTION(6, "EXT_RXD3"),
		MTK_FUNCTION(7, "DBG_MON_B[9]")
	),
	MTK_PIN(
		PINCTRL_PIN(44, "EINT12"),
		"V23", "mt8127",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO44"),
		MTK_FUNCTION(1, "CLKM5"),
		MTK_FUNCTION(2, "PWM0"),
		MTK_FUNCTION(3, "KCOL3"),
		MTK_FUNCTION(4, "ANT_SEL4"),
		MTK_FUNCTION(5, "DPI_D11"),
		MTK_FUNCTION(6, "EXT_TXEN"),
		MTK_FUNCTION(7, "DBG_MON_B[10]")
	),
	MTK_PIN(
		PINCTRL_PIN(45, "EINT13"),
		"Y21", "mt8127",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO45"),
		MTK_FUNCTION(4, "ANT_SEL5"),
		MTK_FUNCTION(5, "DPI_D0"),
		MTK_FUNCTION(6, "SPDIF"),
		MTK_FUNCTION(7, "DBG_MON_B[11]")
	),
	MTK_PIN(
		PINCTRL_PIN(46, "EINT14"),
		"F23", "mt8127",
		MTK_EINT_FUNCTION(0, 14),
		MTK_FUNCTION(0, "GPIO46"),
		MTK_FUNCTION(2, "DAC_DAT_OUT"),
		MTK_FUNCTION(4, "ANT_SEL1"),
		MTK_FUNCTION(5, "CONN_MCU_DBGACK_N"),
		MTK_FUNCTION(6, "NCLE"),
		MTK_FUNCTION(7, "DBG_MON_A[14]")
	),
	MTK_PIN(
		PINCTRL_PIN(47, "EINT15"),
		"G23", "mt8127",
		MTK_EINT_FUNCTION(0, 15),
		MTK_FUNCTION(0, "GPIO47"),
		MTK_FUNCTION(2, "DAC_WS"),
		MTK_FUNCTION(4, "ANT_SEL2"),
		MTK_FUNCTION(5, "CONN_MCU_DBGI_N"),
		MTK_FUNCTION(6, "NCEB1"),
		MTK_FUNCTION(7, "DBG_MON_A[15]")
	),
	MTK_PIN(
		PINCTRL_PIN(48, "EINT16"),
		"H23", "mt8127",
		MTK_EINT_FUNCTION(0, 16),
		MTK_FUNCTION(0, "GPIO48"),
		MTK_FUNCTION(2, "DAC_CK"),
		MTK_FUNCTION(4, "ANT_SEL3"),
		MTK_FUNCTION(5, "CONN_MCU_TRST_B"),
		MTK_FUNCTION(6, "NCEB0"),
		MTK_FUNCTION(7, "DBG_MON_A[16]")
	),
	MTK_PIN(
		PINCTRL_PIN(49, "EINT17"),
		"J22", "mt8127",
		MTK_EINT_FUNCTION(0, 17),
		MTK_FUNCTION(0, "GPIO49"),
		MTK_FUNCTION(1, "UCTS0"),
		MTK_FUNCTION(3, "CLKM0"),
		MTK_FUNCTION(4, "IDDIG"),
		MTK_FUNCTION(5, "ANT_SEL4"),
		MTK_FUNCTION(6, "NREB"),
		MTK_FUNCTION( "CONN_MCU_TRSTW[W